name: Java

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v3

      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'
          cache: 'gradle'

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "refactor(projects): apply google java format"