name: Spring

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  PROPERTIES_PATH: src/main/resources
  PROPERTIES_EXTENSION: properties

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'
          cache: 'gradle'

      - name: Create *.dev.properties
        run: |
          echo "${{ secrets.JPA_DEV_PROPERTIES }}" > ${{ env.PROPERTIES_PATH }}/jpa.dev.${{ env.PROPERTIES_EXTENSION }}
          echo "${{ secrets.SECURITY_DEV_PROPERTIES }}" > ${{ env.PROPERTIES_PATH }}/security.dev.${{ env.PROPERTIES_EXTENSION }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build